#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")"

if [[ "${DEBUG:-}" == "1" ]]; then
  cc_args="-O0 -g -fsanitize=address -D TURBOSTORE_DEBUG"
else
  cc_args="-O3 -flto"
fi

gcc --std=c18 -Wall -Wextra -Werror $cc_args -D _GNU_SOURCE -march=native -o main -l pthread ext/xxHash/xxhash.c src/**/*.c src/*.c
sudo ./main $@
