#!/usr/bin/env bash

set -Eexo pipefail

if [[ $DEBUG == "1" ]]; then
  gcc -std=c18 -Wall -Wextra -Werror -O0 -g -march=native -l pthread -o main main.c
  gdb -ex=r ./main
else
  gcc -std=c18 -Wall -Wextra -Werror -O3 -flto -march=native -l pthread -o main main.c
  ./main
fi
